Dev
arthurtsenin/Innowise-Lab-Internship-Level-1-Clever-to-do-list pull request #1
Opened 2023-02-07 17:49 UTC by arthurtsenin

2023-02-08 12:31 UTC, trigsen requested changes

2023-02-08 12:31 UTC, qtrgq commented on src/App.jsx
> +import { Header } from './components/containers/header/Header';
Добавь алиасы для путей

2023-02-08 12:31 UTC, qtrgq commented on src/api/firebase.config.js
> +export const auth = getAuth();
сделай отдельные сервисы для взаимодействия с бд и аутентификацией

2023-02-08 12:31 UTC, qtrgq commented on src/components/containers/calendarItem/CalendarItem.jsx
> +export const CalendarItem = ({ day, weekDay, monthNumber, month, className, onClick }) => {
используй React.memo

2023-02-08 12:31 UTC, qtrgq commented on src/components/containers/calendarItem/CalendarItem.jsx
> +  };
Вынеси в util функции, они пересоздаются на каждый ререндер компонента

2023-02-08 12:31 UTC, qtrgq commented on src/components/containers/calendarItem/CalendarItem.jsx
> +  }, [todos]);
Зачем тут useState и useEffect ? Ты можешь сразу вызывать в условии проверку

Было:
`todoDays ? <DotHasTask /> : null`

Стало:

`const anyName = useMemo(() => findDaysWithTasks(todos), [todos])`

`anyName && <DotHasTask />`

2023-02-08 12:31 UTC, qtrgq commented on src/components/containers/calendarItem/CalendarItem.jsx
> +          {taskCompleted ? <DotHasCheckedTask /> : null}
В комменте выше описал

```
const anyName = useMemo(() => findDaysWithTasks(todos), [todos])

anyName && <DotHasTask />
```

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +import moment from 'moment';
moment теперь депрекейтед и не поддерживается, используй либо другую библиотеку (daysjs) либо используй `Date` из js

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +import 'slick-carousel/slick/slick-theme.css';
почему тут, а не в главном файле app ?

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +  const [value, setValue] = useState(moment());
то же что и с комментом про moment

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +  }, []);
Зачем обращаться через ref к элементу напрямую в DOM для onWheel ивента, если можно пробросить onWheel в сам `div` элемент ?

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +  }, []);
Почему не пробросить onScroll в элемент div, зачем это делать через ref

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +  }, [week]);
Зачем useEffect + useState ?

`const calendar = useMemo(() => buildCalendar(value, week), [value, week])`

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +          <Date>Choosen date: {value.format(DATE_FORMAT)}</Date>
Для взаимодействия с датами создай отдельный сервис

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +            Completed Tasks: {todos.filter((todo) => todo.completed === true).length}
```suggestion
            Completed Tasks: {todos.filter((todo) => todo.completed).length}
```

2023-02-08 12:31 UTC, qtrgq commented on src/components/containers/calendarList/CalendarList.jsx
> +            Completed Tasks: {todos.filter((todo) => todo.completed === true).length}
Вынеси в useMemo

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +              key={index}
ключи не должны быть индексами

2023-02-08 12:31 UTC, qtrgq commented on src/components/containers/calendarList/CalendarList.jsx
> +                day.isSame(moment(), 'day') ? 'current' : value.isSame(day, 'day') ? 'chosen' : ''
Для взаимодействия с датами создай отдельный сервис

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +              month={day.format('MMMM')}
Для взаимодействия с датами создай отдельный сервис

2023-02-08 12:31 UTC, qtrgq commented on src/components/containers/calendarList/CalendarList.styles.js
> +  } */
комменты удалить

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/clock/Clock.jsx
> +    const secondsOuter = seconds < 10 ? '0' + seconds : seconds;
работа с датами в отдельном сервисе

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/header/Header.jsx
> +      localStorage.setItem('user', JSON.stringify(null));
```suggestion
      localStorage.removeItem('user');
```

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/header/Header.jsx
> +          checked={theme.changeTheme.type === 'dark' ? true : false}
```suggestion
          checked={theme.changeTheme.type === 'dark'}
```

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/header/Header.jsx
> +        ) : null}
```suggestion
        {user && (
          <Fragment>
            <Email>User Email: {user && user.email}</Email>
            <Button onClick={handleLogout}>
              <LogoutIcon mr={5} />
              Logout
            </Button>
          </Fragment>
        )}
```

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/header/Header.jsx
> +            <Email>User Email: {user && user.email}</Email>
```suggestion
            <Email>User Email: {user?.email}</Email>
```

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/header/Header.jsx
> +          </Fragment>
```suggestion
          <>
            <Email>User Email: {user && user.email}</Email>
            <Button onClick={handleLogout}>
              <LogoutIcon mr={5} />
              Logout
            </Button>
          </>
```

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/header/Header.styles.js
> +  background-color: ${MAIN_COLOR.background};
сделать через тему

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/loader/Loader.styles.js
> +  min-height: 100vh;
100vh -> 100%

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/sign/Sign.jsx
> +  };
вынеси за пределы компонента

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/sign/Sign.jsx
> +        : Swal.fire({
Переделай всю функцию

1) Одна функция отвечает за одно действие. А не за регистрацию и логин
2) Создай обертки для переиспользования своих тост компонентов

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/sign/Sign.jsx
> +      ) : (
```suggestion
  if (isLoading) {
  <Loader loading={isLoading} />
  }

  return (
    <>
```

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/sign/Sign.jsx
> +              </>
сделай два разных компонента. один для логина другой для регистрации

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoItem/ToDoItem.jsx
> +        checked={todo.completed ? true : false}
```suggestion
        checked={todo.completed}
```

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +  if (moment(date).add(1, 'day').isBefore(new Date())) {
взаимодействие с датами в отдельном сервисе

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +  }
это должно быть в useEffect

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +    });
отдельный сервис для работы с базой данных

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +    update(ref(db, `/${auth.currentUser.uid}/${todo.uidd}`), { completed: !todo.completed });
отдельный сервис для работы с базой данных

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +    });
отдельный сервис для работы с базой данных

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +    remove(ref(db, `/${auth.currentUser.uid}/${uid}`));
отдельный сервис для работы с базой данных

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +          onChange={(e) => setTitle(e.target.value)}
вынеси в отдельную функцию в компоненте

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +          onChange={(e) => setDescription(e.target.value)}
вынеси в отдельную функцию в компоненте

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +          onChange={(e) => setDate(e.target.value)}
вынеси в отдельную функцию в компоненте

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +            disabled={!title || moment(date).add(1, 'day').isBefore(new Date())}
сервис для дат

2023-02-08 12:31 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +            disabled={!title || moment(date).add(1, 'day').isBefore(new Date())}
сервис для дат

2023-02-08 12:31 UTC, trigsen commented on src/context/ThemeContext.jsx
> +    localStorage.getItem('theme') ? JSON.parse(localStorage.getItem('theme') || '') : THEMES.light
сделать проверку что элемент из локал стораджа это именно тема, а не другая строка

2023-02-08 12:31 UTC, trigsen commented on src/context/ThemeContext.jsx
> +    setTheme(theme.type === 'light' ? THEMES.dark : THEMES.light);
```suggestion
    setTheme(theme.type === THEMES.light ? THEMES.dark : THEMES.light);
```

2023-02-08 12:31 UTC, trigsen commented on src/context/ThemeContext.jsx
> +  }, [theme]);
сохраняй в функции где ты меняешь тему, а не в useEffect

2023-02-08 12:31 UTC, trigsen commented on src/context/TodoContext.jsx
> +        onValue(ref(db, `/${auth.currentUser.uid}`), (snapshot) => {
работа с бд в отдельном сервисе

2023-02-08 12:31 UTC, trigsen commented on src/context/TodoContext.jsx
> +          if (data !== null) {
```suggestion
          if (data) {
```

2023-02-08 12:31 UTC, qtrgq commented on src/pages/HomePage/HomePage.styles.js
> +  height: 100vh;
100vh -> 100%

2023-02-08 12:31 UTC, qtrgq commented on src/pages/SigninPage/SigninPage.jsx
> +      <Sign isSign={true} />
```suggestion
      <Sign isSign />
```

2023-02-08 12:31 UTC, qtrgq commented on src/pages/SigninPage/SigninPage.styles.js
> +  height: 100vh;
vh -> %

2023-02-08 12:31 UTC, qtrgq commented on src/pages/SignupPage/SignupPage.jsx
> +      <Sign isSign={false} />
отдельные страницы для логина и регистрации

2023-02-08 12:31 UTC, qtrgq commented on src/pages/SignupPage/SignupPage.styles.js
> +  height: 100vh;
проценты

2023-02-08 12:31 UTC, qtrgq commented on src/utils/buildCalendar.js
> +  const startDay = moment();
сервис для работы с датами

2023-02-10 09:22 UTC, qtrgq commented on craco.config.js
> +    alias: {
🚀

2023-02-10 09:22 UTC, qtrgq commented on craco.config.js
> +      '@Api': path.resolve(__dirname, 'src/api'),
можешь назвать их с маленькой буквы `@api` и тд

2023-02-10 09:22 UTC, qtrgq commented on src/api/authHelper.js
> +};
Эти методы тебе не нужны. Тут у тебя хелперы, которые связаны с аутентификацией. Эти функции просто делегируют в todo хелперы. Используй напрямую `deleteTodo` вместо `authDeleteTodo` и с остальными тоже самое

2023-02-10 09:22 UTC, qtrgq commented on src/api/dateHelper.js
> +};
это функци не связана с датами, она больше про календарь. Ее надо вынести в utils в компоненте календаря, и в ней вместо dayjs() напрямую, дергать твои хелперы для даты

2023-02-10 09:22 UTC, trigsen commented on src/api/dateHelper.js
> +};
Эта функци тоже не относится напрямую к датам. 

Тебе нужно сделать функцию `isSame`, которую ты будешь дергать в своем компоненте

2023-02-10 09:22 UTC, trigsen commented on src/components/containers/calendarItem/CalendarItem.jsx
> +      <StyledCalendarItem theme={theme} className={markerDay(value, day)} onClick={onClick}>
Посмотри коммент выше про markerDay

2023-02-10 09:22 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +    if (e.deltaY == 0) return;
`if (e.deltaY)`

2023-02-10 09:22 UTC, trigsen commented on src/components/containers/calendarList/CalendarList.jsx
> +      Math.trunc((e.target.scrollLeft / e.target.scrollWidth) * 100) < 70
вынеси цифры в переменные

2023-02-10 09:22 UTC, trigsen commented on src/components/containers/header/Header.jsx
> +          checked={theme.changeTheme.type === 'dark'}
Вынеси переменные для тем в enum

2023-02-10 09:22 UTC, trigsen commented on src/components/containers/header/Header.styles.js
> +// import { MAIN_COLOR } from '../../../constants/mainColor';
коммент

2023-02-10 09:22 UTC, trigsen commented on src/components/containers/signIn/SignIn.jsx
> +      await localStorage.setItem('user', JSON.stringify(data.email));
перемести localStorage в функцию signIn

2023-02-10 09:22 UTC, trigsen commented on src/components/containers/signUp/SignUp.jsx
> +      await localStorage.setItem('user', JSON.stringify(data.email));
локал сторадж функцию в createUser

2023-02-10 09:22 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +} from '../../../api/authHelper';
alias

2023-02-10 09:22 UTC, trigsen commented on src/components/views/toasts/ErrorDateChoose.js
> +export const ErrorDateChoose = () => {
с маленькой буквы, это фукнция. Добавь глагол в начале названия

2023-02-10 09:22 UTC, trigsen commented on src/pages/SigninPage/SigninPage.styles.js
> +  position: absolute;
зачем абсолют

2023-02-10 11:21 UTC, arthurtsenin commented on src/pages/SigninPage/SigninPage.styles.js
> +  position: absolute;
без absolute не корректно работает смена темы(фон)

2023-02-10 13:29 UTC, trigsen commented on src/pages/SigninPage/SigninPage.styles.js
> +  position: absolute;
Это не есть хорошо. Разберись почему и сделай так, чтобы работало без абсолюта.

2023-02-10 13:32 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +          <PrimaryButton disabled={!title || validateDate(date)} onClick={handleEditConfirm}>
вынеси это условие disabled в переменную и переиспользуй ее для остальных пропов

2023-02-10 13:32 UTC, trigsen commented on src/components/containers/toDoList/ToDoList.jsx
> +          .filter((todo) => todo.createdAt === getChoosenDay(chosenDate))
вынеси это выше в useMemo. При каждом ререндре фильтрация будет снова происходить даже если не поменяется chosenDate

2023-02-10 13:32 UTC, trigsen commented on craco.config.js
>    webpack: {
Общий коммент для всего проекта:

1) Добавь React.memo
2) Используй useMemo и useCallback, там где нужно

2023-02-15 10:02 UTC, trigsen approved these changes
Делай деплой приложения. В следующий понедельник делаешь демо проекта

2023-02-15 11:33 UTC, merged